image: alpine:latest

services:
  - docker:dind

before_script:
  - apk add --no-cache curl jq python3 py-pip git openssh-client bash
  - pip install awscli
  - mkdir ~/.ssh
  - echo $REACT_DEPLOY_TOKEN > ~/.ssh/id_ed25519
  - chmod 644 ~/.ssh/id_ed25519
  
stages:
  - build

build:
  stage: build
  script:
    - rm -rf client
    - git clone git@gitlab.com:lucidsystems/client-projects/casual-precision/casual-spend-planner-react.git ./client/
    - ls ./client/
    # - $(aws ecr get-login --no-include-email --region us-west-1)
    # - docker build -t $AWS_ECR_URL .
    # - docker push $AWS_ECR_URL
  only:
    - master
  tags:
    - docker
